In [7]:
neurons_path = 'neurons.csv.gz'
connect_path = 'connections_princeton.csv.gz'

In [8]:
import pandas as pd
neurons_df = pd.read_csv(neurons_path, compression='gzip')
connect_df = pd.read_csv(connect_path, compression='gzip')

In [9]:
neurons_df

,Root ID,Top in/out region,Community labels,Predicted NT type,Predicted NT confidence,Verified NT type,Verified Neuropeptide,Body Part,Function,Flow,...,Class,Sub Class,Hemilineage,Nerve,Soma side,Primary Cell Type,Alternative Cell Type(s),Cable length (nm),Surface area (nm^2),Volume (nm^3)
0,720575940381905254,NO_CONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,720575940386709331,NO_CONS,soma in brain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,720575940387110289,NO_CONS,sensory neuron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,720575940389711170,NO_CONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,720575940407089948,NO_CONS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115146,720575941733218347,SAD.AVLP,NaN,ACH,0.87,NaN,NaN,NaN,NaN,intrinsic,...,NaN,NaN,ALl1_ventral,NaN,right,CB1817a,CB1817a,NaN,NaN,NaN
115147,720575941733241899,SAD.AMMC,NaN,GABA,0.71,NaN,NaN,antenna,"auditory_high_frequency,proprioception",afferent,...,chordotonal_organ_neuron,johnstons_organ_B_neuron,NaN,left_antennal_nerve,left,JO-B,JO-B,NaN,NaN,NaN
115148,720575941733258795,AMNP,NaN,ACH,0.72,NaN,NaN,wing_margin,tactile,afferent,...,bristle_neuron,wing_margin_bristle_neuron,NaN,right_anterior_dorsal_mesothoracic_nerve,right,SNta11,SNta11,NaN,NaN,NaN
115149,720575941733260075,ME,soma in brain,GABA,0.34,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,right,NaN,NaN,NaN,NaN,NaN
115150,720575941733281579,T2_MESONM,NaN,GABA,0.79,NaN,NaN,middle_leg,proprioception,afferent,...,orphan_neuron,middle_leg_orphan_neuron,NaN,left_mesothoracic_leg_nerve,left,SNppxx,SNppxx,NaN,NaN,NaN

In [10]:
connect_df

,pre_root_id,post_root_id,neuropil,syn_count,nt_type
0,720575941350274352,720575941399414563,VNC_T1_ProNm_R,28,NaN
1,720575941350274352,720575941399414563,VNC_unassigned_R,2,NaN
2,720575941350274352,720575941409918831,VNC_T1_ProNm_R,3,NaN
3,720575941350274352,720575941425044820,VNC_T3_MetaNm_R,3,NaN
4,720575941350274352,720575941434753568,VNC_T2_MesoNm_R,9,NaN
...,...,...,...,...,...
3777041,720575941733281579,720575941617250431,VNC_T2_MesoNm_L,3,NaN
3777042,720575941733281579,720575941623072970,VNC_T2_MesoNm_L,5,NaN
3777043,720575941733281579,720575941640436255,VNC_T2_MesoNm_L,6,NaN
3777044,720575941733281579,720575941645063329,VNC_T2_MesoNm_L,5,NaN
3777045,720575941733281579,720575941686672246,VNC_T2_MesoNm_L,4,NaN